#!/usr/bin/env python3
"""AGENT 7 - qualified member audit.

Catches the exact bug class that broke v1.19.2:
    ToolExecutor.SUPPORTED_TOOLS   <- symbol existed in the FILE,
                                      but inside a DIFFERENT class.

Agent 1 indexes declarations file-wide, so it said "resolves".
Agent 7 is stricter: for every `Type.member` reference where `Type` is one of
our own top-level classes/objects, it checks the member is declared inside
THAT type's own body (including its companion object).
"""
import os, re, sys

# Resolve the app tree from this script's own location so the agent works from
# any checkout (CI included); override with ROOT=/path if the layout differs.
ROOT = os.environ.get(
    "ROOT",
    os.path.normpath(
        os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..", "..", "app", "src", "main", "java", "com", "jarvis", "ai",
        )
    ),
)

DECL = re.compile(r"^(?P<indent>[ \t]*)(?:@\w+\s+)*"
                  r"(?:public |internal |private |abstract |open |sealed |data |enum )*"
                  r"(?P<kind>class|object|interface)\s+(?P<name>[A-Z]\w*)")
MEMBER = re.compile(r"^[ \t]*(?:@\w+\s+)*"
                    r"(?:public |internal |private |protected |override |open |abstract |const |lateinit |suspend |inline |operator |external )*"
                    r"(?:val|var|fun)\s+(?:<[^>]*>\s*)?(?P<name>\w+)")
ENUM_ENTRY = re.compile(r"^[ \t]*(?P<name>[A-Z][A-Z0-9_]*)\s*[,;(]")
NESTED = re.compile(r"^[ \t]*(?:@\w+\s+)*"
                    r"(?:public |internal |private |abstract |open |sealed |data |enum )*"
                    r"(?:class|object|interface)\s+(?P<name>[A-Z]\w*)")


def kt_files():
    for base, _, files in os.walk(ROOT):
        for f in files:
            if f.endswith(".kt"):
                yield os.path.join(base, f)


def brace_span(lines, start):
    """Return (end_index_exclusive) of the block opened on/after line `start`."""
    depth = 0
    opened = False
    for i in range(start, len(lines)):
        code = strip_noise(lines[i])
        for ch in code:
            if ch == "{":
                depth += 1
                opened = True
            elif ch == "}":
                depth -= 1
                if opened and depth == 0:
                    return i + 1
        if opened and depth == 0:
            return i + 1
    return len(lines)


def strip_noise(line):
    line = re.sub(r'"(?:\\.|[^"\\])*"', '""', line)
    line = re.sub(r"//.*$", "", line)
    return line


def build_index():
    """type name -> set of member names declared inside its own body."""
    members = {}
    owners = {}
    for path in kt_files():
        lines = open(path, encoding="utf-8").read().split("\n")
        # Single-line enum bodies (`enum class E { A, B, C }`) are missed by the
        # line-anchored ENUM_ENTRY regex below, because the body lives on the
        # declaration line itself. Index them explicitly here; the token set is
        # the union, so this can only add real entries, never remove them.
        raw = "\n".join(lines)
        for m in re.finditer(
            r"enum\s+class\s+(?P<name>[A-Z]\w*)\s*\{(?P<body>[^{}]*)\}", raw
        ):
            for tok in re.findall(r"[A-Z][A-Z0-9_]*", m.group("body")):
                members.setdefault(m.group("name"), set()).add(tok)
        for i, line in enumerate(lines):
            m = DECL.match(strip_noise(line))
            if not m or m.group("indent"):
                continue  # only top-level declarations
            name = m.group("name")
            end = brace_span(lines, i)
            body = lines[i + 1:end]
            found = set()
            for b in body:
                b = strip_noise(b)
                mm = MEMBER.match(b)
                if mm:
                    found.add(mm.group("name"))
                ee = ENUM_ENTRY.match(b)
                if ee:
                    found.add(ee.group("name"))
                nn = NESTED.match(b)
                if nn:
                    found.add(nn.group("name"))
            members.setdefault(name, set()).update(found)
            owners[name] = os.path.relpath(path, ROOT)
    return members, owners


USE = re.compile(r"\b(?P<type>[A-Z]\w*)\.(?P<member>[A-Za-z_]\w*)")
SKIP_TYPES = {"Log", "Build", "Color", "Math", "String", "Int", "Long", "Uri",
              "Intent", "Context", "Settings", "Toast", "View", "R", "Modifier",
              "Arrangement", "Alignment", "FontWeight", "TextAlign", "Dispatchers",
              "System", "Locale", "TimeUnit", "Base64", "JSONObject", "JSONArray",
              # javax.mail.Message collides with com.jarvis.ai.data.model.Message;
              # the local data class has no qualified members, so skipping costs
              # nothing and stops `Message.RecipientType` being misattributed to it.
              "Message"}
# Members generated by the kotlinx.serialization compiler plugin rather than
# declared in source (`@Serializable class Foo` gets a synthetic Foo.serializer()).
# Without this skip every serializable DTO would look undeclared.
# valueOf/values/entries are the JVM/Kotlin enum synthetics every enum class gets.
SKIP_MEMBERS = {"serializer", "valueOf", "values", "entries"}

# Extension functions (`fun PlanStatus.isTerminal()`) are valid calls but are not
# declared inside the receiver's body, so the member index cannot see them.
# Collected across all files and treated as globally valid.
EXT_FUN = re.compile(r"\bfun\s+(?P<type>[A-Z]\w*)\.(?P<member>[A-Za-z_]\w*)\s*\(")
extensions = set()
for _p in kt_files():
    _t = open(_p, encoding="utf-8").read()
    for _m in EXT_FUN.finditer(_t):
        extensions.add((_m.group("type"), _m.group("member")))


def main():
    members, owners = build_index()
    findings = []
    for path in kt_files():
        rel = os.path.relpath(path, ROOT)
        text = open(path, encoding="utf-8").read()
        for n, raw in enumerate(text.split("\n"), 1):
            line = strip_noise(raw)
            if line.strip().startswith(("import ", "package ", "*", "/*")):
                continue
            for m in USE.finditer(line):
                t, mem = m.group("type"), m.group("member")
                if t in SKIP_TYPES or t not in members:
                    continue
                if mem in SKIP_MEMBERS:
                    continue  # compiler-synthetic (kotlinx.serialization / enum)
                if (t, mem) in extensions:
                    continue  # declared as an extension function elsewhere
                if mem[0].isupper() and mem.isupper() is False and mem in members:
                    continue  # Type.NestedType chain
                if mem in members[t]:
                    continue
                findings.append((rel, n, t, mem, raw.strip()[:90]))

    print("AGENT 7 (qualified members): %d of our types indexed" % len(members))
    if not findings:
        print("  OK - every Type.member reference exists inside that type")
        return 0
    for rel, n, t, mem, src in findings:
        print("  FAIL %s:%d  %s.%s not declared in %s (%s)"
              % (rel, n, t, mem, t, owners.get(t, "?")))
        print("       %s" % src)
    print("  %d suspicious reference(s)" % len(findings))
    return 1


if __name__ == "__main__":
    sys.exit(main())
